---
apiVersion: apps/v1
Kind: deployment 
metadata:
  name: simple-service
  labels:
    app: simple-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: simple-service
  template:
    metadata:
      labels:
        app: simple-service
    spec:
      containers:
      - name: simple-service
        image: nginx
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service 
metadata:
  name: simple-service
spec:
  type: ClusterIP
  selector:
    app: simple-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-app-ingress
  annotations:
    something: something
spec:
  ingressClassName: nginx 
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: simple-service
            port: 
              number: 80
