---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: user-service
  labels:
    app: user-service
spec: 
  replicas: 1
  strategy: 
    type: RollingUpdate
    RollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: pttgcacr.azurecr.io/user-service:unstable
        ports:
        - containerPort: 80
--- 
apiVersion: v1
kind: Service 
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service-ingress
  annotations:
    something: something
spec:
  ingressClassName: nginx 
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: user-service
            port: 
              number: 80
